language: python
python:
- '3.4'
- '3.5'
- '3.6'
- '3.7'
matrix:
  allow_failures:
    - python: '3.7'
install:
- pip install flake8==2.5.0
- pip install requests
script:
- flake8 . --max-complexity 5 --max-line-length 99 --ignore E201,E202,E402
- python -m doctest README.md
- python -m doctest examples.md
- python setup.py test
notifications:
  email: false
deploy:
  provider: pypi
  user: jwg
  on:
    python: '3.5'
    branch: 'master'
  password:
    secure: CHNPYcaIlpzGsIZ/s0FKG9Yaj8uUa1fE5LwVwgh/JjxLK+E+ppYlInK9Ci2C/WJlWYX867agDOPkFXKFnZwUpTqfs7uQ836wwFsbtk8JZaxWAWl/D5b+oGwWzgd0N+a/0qvB2uk6OoYw2z76hNn5wEMkgKfarbsEr8LHYg+s20RUmAOHH9CYtZI0QfKYzoHFdnuxOGkOftqU1Nw6kQhMwdGjrvAbzNEcfbP13EV3QENx/qMa3t7sneA65KC6qAgXi818FmGlthjBdnPMpDe5tRPtdReGWMB5jBrwGs21l+zh0Kgk8lCaLspZe227uF2YTJ2aMHBfeBSDWM9Opl1P+OrYNrI5q2Natgc575fEsvXPdP29yNVGvY14dvyUMzkz4pTHPOYM9I03X3sP0t2kSRuiynK0zNdayEy1tAaLsbbOZ++FohGtVgYX1k0lPPqwJXZIWf1lec0NLg7QeaNRPz4LS2JeR/AdF2H9pE5sX8Q9VA/xvgf0GBvKzV52P98DRNB2f06WG7bGEnE2sTOaiGFgplZoS9no5vCXUKOS+CpLIMoz6928mLCnrhJuzOSu6tqrnGp3oVQ5GLQJN0vwiZ5lQmacUXZL4jrTD1tTyyQ+Pe9kGFlxerAJZ7O1rIrM1x8rPYTIY+ADGN3wdM+JF1A9L8hP4j25xeZNpd7IxMs=
