language: python
python:
- '3.4'
- '3.5'
- '3.6'
- '3.7'
matrix:
  allow_failures:
    - python: '3.7'
install:
- pip install flake8==2.5.0
script:
- flake8 . --max-complexity 5 --max-line-length 99 --ignore E201,E202,E402
- python -m doctest README.md
- python -m doctest examples.md
- python setup.py test
notifications:
  email: false
deploy:
  provider: pypi
  user: jwg
  on:
    python: '3.5'
    branch: 'master'
  password:
    secure: 