language: python
python:
- '3.4'
- '3.5'
- '3.6'
- '3.7'
matrix:
  allow_failures:
    - python: '3.7'
install:
- pip install flake8==2.5.0
script:
- flake8 . --max-complexity 5 --max-line-length 99 --ignore E201,E202,E402
- python -m doctest README.md
- python -m doctest examples.md
- python setup.py test
notifications:
  email: false
deploy:
  provider: pypi
  user: jwg
  on:
    python: '3.5'
    branch: 'master'
  password:
    secure: goL6ZwfWLb+MTPXMVYtpAYdHJ4pJNxq+zFD2cuuUPOKzOif+TMn7pENTFTeVmuYxzMCSdY0R9lFDdHhue5TgYtJ6FSB/a+BFs75653OekTErhR6SBeJgrglJlb1aM+dzVOrsKBB2jppbcbM+ZMkYf2PKC8T4Zxq7dsjxt/acGYRW9msMLyYCGWNZnMIQW3gZKC29/etQULkbpZWCbP6yg2Un8pPK/7cpIMuvholGtyWAtoL0Ruy4wATpemJuXh0D3kWupZ5vRjzS8Nz//fsrVx84m9bNPex6TW1dffr9XnIn0Fdm0OHXYRMprK5WUzK8ow9pTPO177Ku3lhFX90B0Bur4VXv0NkgLgKqksoMvz/7EWqe4frkgZL8QJBrynfFANl/zd1UBoLdJgF4lG/ojzb9jrq1+URAvoqwyfOD0YfNWfLgN3zhX/ZcuW61jndSiCMxT5jOtvfzKtyUCfgFaOSsWahHDkqczYe0vkur84PdF9CIjJ73tHjOvlwc4G17R213jUamNtVnauKEzlTeUAiWFFrdGv6eGT71zIaA1l3T8yrfMGKoJVyNl11CcA1tXFnBkN01Ci6spBmPI6OvosHEbPKQJ6Cb2TowzLD37/OHHHAu5LIG50DFB0a+UfDI1+Tg+mQjju7eKitManQG4o4tFn8979gCh2oTMisZTw8=